/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PromptType = IDL.Variant({
  'role' : IDL.Null,
  'scene' : IDL.Null,
  'location' : IDL.Null,
});
export const ProjectId = IDL.Nat;
export const Prompt = IDL.Record({
  'title' : IDL.Text,
  'promptText' : IDL.Text,
  'promptType' : PromptType,
  'systemMessage' : IDL.Opt(IDL.Text),
  'project' : ProjectId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Scene = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Metadata = IDL.Record({
  'narrativeStructure' : IDL.Opt(
    IDL.Variant({
      'episodic' : IDL.Null,
      'nonLinear' : IDL.Null,
      'linear' : IDL.Null,
    })
  ),
  'originalLanguage' : IDL.Opt(IDL.Text),
  'productionScope' : IDL.Opt(
    IDL.Variant({ 'large' : IDL.Null, 'small' : IDL.Null, 'medium' : IDL.Null })
  ),
  'visualStyle' : IDL.Opt(IDL.Text),
  'tone' : IDL.Opt(
    IDL.Variant({
      'humorous' : IDL.Null,
      'dark' : IDL.Null,
      'serious' : IDL.Null,
      'lighthearted' : IDL.Null,
    })
  ),
  'complexityLevel' : IDL.Opt(
    IDL.Variant({
      'complex' : IDL.Null,
      'simple' : IDL.Null,
      'moderate' : IDL.Null,
    })
  ),
  'intendedAudience' : IDL.Opt(IDL.Text),
  'genre' : IDL.Opt(IDL.Text),
  'scriptFormat' : IDL.Opt(
    IDL.Variant({
      'animated' : IDL.Null,
      'standard' : IDL.Null,
      'musical' : IDL.Null,
    })
  ),
  'runtime' : IDL.Opt(
    IDL.Variant({ 'short' : IDL.Null, 'featureLength' : IDL.Null })
  ),
});
export const Project = IDL.Record({
  'title' : IDL.Text,
  'scenes' : IDL.Vec(Scene),
  'metadata' : IDL.Opt(Metadata),
  'user' : IDL.Principal,
  'logLine' : IDL.Text,
  'synopsis' : IDL.Text,
  'roles' : IDL.Vec(IDL.Text),
  'prompts' : IDL.Vec(Prompt),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPromptEntry' : IDL.Func([Prompt], [ProjectId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMovieProject' : IDL.Func([Project], [ProjectId], []),
  'createPromptEntry' : IDL.Func([Prompt], [Prompt], []),
  'deleteMovieProject' : IDL.Func([ProjectId], [], []),
  'getAllUserProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMovieProject' : IDL.Func([ProjectId], [Project], ['query']),
  'getPrompt' : IDL.Func([ProjectId], [Prompt], ['query']),
  'getPromptEntries' : IDL.Func([], [IDL.Vec(Prompt)], ['query']),
  'getRolePromptEntries' : IDL.Func([], [IDL.Vec(Prompt)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMovieProject' : IDL.Func([ProjectId, Project], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PromptType = IDL.Variant({
    'role' : IDL.Null,
    'scene' : IDL.Null,
    'location' : IDL.Null,
  });
  const ProjectId = IDL.Nat;
  const Prompt = IDL.Record({
    'title' : IDL.Text,
    'promptText' : IDL.Text,
    'promptType' : PromptType,
    'systemMessage' : IDL.Opt(IDL.Text),
    'project' : ProjectId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Scene = IDL.Record({ 'title' : IDL.Text, 'description' : IDL.Text });
  const Metadata = IDL.Record({
    'narrativeStructure' : IDL.Opt(
      IDL.Variant({
        'episodic' : IDL.Null,
        'nonLinear' : IDL.Null,
        'linear' : IDL.Null,
      })
    ),
    'originalLanguage' : IDL.Opt(IDL.Text),
    'productionScope' : IDL.Opt(
      IDL.Variant({
        'large' : IDL.Null,
        'small' : IDL.Null,
        'medium' : IDL.Null,
      })
    ),
    'visualStyle' : IDL.Opt(IDL.Text),
    'tone' : IDL.Opt(
      IDL.Variant({
        'humorous' : IDL.Null,
        'dark' : IDL.Null,
        'serious' : IDL.Null,
        'lighthearted' : IDL.Null,
      })
    ),
    'complexityLevel' : IDL.Opt(
      IDL.Variant({
        'complex' : IDL.Null,
        'simple' : IDL.Null,
        'moderate' : IDL.Null,
      })
    ),
    'intendedAudience' : IDL.Opt(IDL.Text),
    'genre' : IDL.Opt(IDL.Text),
    'scriptFormat' : IDL.Opt(
      IDL.Variant({
        'animated' : IDL.Null,
        'standard' : IDL.Null,
        'musical' : IDL.Null,
      })
    ),
    'runtime' : IDL.Opt(
      IDL.Variant({ 'short' : IDL.Null, 'featureLength' : IDL.Null })
    ),
  });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'scenes' : IDL.Vec(Scene),
    'metadata' : IDL.Opt(Metadata),
    'user' : IDL.Principal,
    'logLine' : IDL.Text,
    'synopsis' : IDL.Text,
    'roles' : IDL.Vec(IDL.Text),
    'prompts' : IDL.Vec(Prompt),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPromptEntry' : IDL.Func([Prompt], [ProjectId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMovieProject' : IDL.Func([Project], [ProjectId], []),
    'createPromptEntry' : IDL.Func([Prompt], [Prompt], []),
    'deleteMovieProject' : IDL.Func([ProjectId], [], []),
    'getAllUserProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMovieProject' : IDL.Func([ProjectId], [Project], ['query']),
    'getPrompt' : IDL.Func([ProjectId], [Prompt], ['query']),
    'getPromptEntries' : IDL.Func([], [IDL.Vec(Prompt)], ['query']),
    'getRolePromptEntries' : IDL.Func([], [IDL.Vec(Prompt)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMovieProject' : IDL.Func([ProjectId, Project], [], []),
  });
};

export const init = ({ IDL }) => { return []; };