/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Metadata {
  'narrativeStructure' : [] | [
    { 'episodic' : null } |
      { 'nonLinear' : null } |
      { 'linear' : null }
  ],
  'originalLanguage' : [] | [string],
  'productionScope' : [] | [
    { 'large' : null } |
      { 'small' : null } |
      { 'medium' : null }
  ],
  'visualStyle' : [] | [string],
  'tone' : [] | [
    { 'humorous' : null } |
      { 'dark' : null } |
      { 'serious' : null } |
      { 'lighthearted' : null }
  ],
  'complexityLevel' : [] | [
    { 'complex' : null } |
      { 'simple' : null } |
      { 'moderate' : null }
  ],
  'intendedAudience' : [] | [string],
  'genre' : [] | [string],
  'scriptFormat' : [] | [
    { 'animated' : null } |
      { 'standard' : null } |
      { 'musical' : null }
  ],
  'runtime' : [] | [{ 'short' : null } | { 'featureLength' : null }],
}
export interface Project {
  'title' : string,
  'scenes' : Array<Scene>,
  'metadata' : [] | [Metadata],
  'user' : Principal,
  'logLine' : string,
  'synopsis' : string,
  'roles' : Array<string>,
  'prompts' : Array<Prompt>,
}
export type ProjectId = bigint;
export interface Prompt {
  'title' : string,
  'promptText' : string,
  'promptType' : PromptType,
  'systemMessage' : [] | [string],
  'project' : ProjectId,
}
export type PromptType = { 'role' : null } |
  { 'scene' : null } |
  { 'location' : null };
export interface Scene { 'title' : string, 'description' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPromptEntry' : ActorMethod<[Prompt], ProjectId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMovieProject' : ActorMethod<[Project], ProjectId>,
  'createPromptEntry' : ActorMethod<[Prompt], Prompt>,
  'deleteMovieProject' : ActorMethod<[ProjectId], undefined>,
  'getAllUserProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMovieProject' : ActorMethod<[ProjectId], Project>,
  'getPrompt' : ActorMethod<[ProjectId], Prompt>,
  'getPromptEntries' : ActorMethod<[], Array<Prompt>>,
  'getRolePromptEntries' : ActorMethod<[], Array<Prompt>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMovieProject' : ActorMethod<[ProjectId, Project], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];