/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Metadata {
    narrativeStructure?: Variant_episodic_nonLinear_linear;
    originalLanguage?: string;
    productionScope?: Variant_large_small_medium;
    visualStyle?: string;
    tone?: Variant_humorous_dark_serious_lighthearted;
    complexityLevel?: Variant_complex_simple_moderate;
    intendedAudience?: string;
    genre?: string;
    scriptFormat?: Variant_animated_standard_musical;
    runtime?: Variant_short_featureLength;
}
export type ProjectId = bigint;
export interface Prompt {
    title: string;
    promptText: string;
    promptType: PromptType;
    systemMessage?: string;
    project: ProjectId;
}
export interface Project {
    title: string;
    scenes: Array<Scene>;
    metadata?: Metadata;
    user: Principal;
    logLine: string;
    synopsis: string;
    roles: Array<string>;
    prompts: Array<Prompt>;
}
export interface UserProfile {
    name: string;
}
export interface Scene {
    title: string;
    description: string;
}
export enum PromptType {
    role = "role",
    scene = "scene",
    location = "location"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_animated_standard_musical {
    animated = "animated",
    standard = "standard",
    musical = "musical"
}
export enum Variant_complex_simple_moderate {
    complex = "complex",
    simple = "simple",
    moderate = "moderate"
}
export enum Variant_episodic_nonLinear_linear {
    episodic = "episodic",
    nonLinear = "nonLinear",
    linear = "linear"
}
export enum Variant_humorous_dark_serious_lighthearted {
    humorous = "humorous",
    dark = "dark",
    serious = "serious",
    lighthearted = "lighthearted"
}
export enum Variant_large_small_medium {
    large = "large",
    small = "small",
    medium = "medium"
}
export enum Variant_short_featureLength {
    short_ = "short",
    featureLength = "featureLength"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPromptEntry(prompt: Prompt): Promise<ProjectId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createMovieProject(newProject: Project): Promise<ProjectId>;
    createPromptEntry(prompt: Prompt): Promise<Prompt>;
    deleteMovieProject(projectId: ProjectId): Promise<void>;
    getAllUserProjects(): Promise<Array<Project>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMovieProject(projectId: ProjectId): Promise<Project>;
    getPrompt(promptId: ProjectId): Promise<Prompt>;
    getPromptEntries(): Promise<Array<Prompt>>;
    getRolePromptEntries(): Promise<Array<Prompt>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateMovieProject(projectId: ProjectId, updatedProject: Project): Promise<void>;
}
import type { Metadata as _Metadata, Project as _Project, ProjectId as _ProjectId, Prompt as _Prompt, PromptType as _PromptType, Scene as _Scene, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPromptEntry(arg0: Prompt): Promise<ProjectId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPromptEntry(to_candid_Prompt_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPromptEntry(to_candid_Prompt_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createMovieProject(arg0: Project): Promise<ProjectId> {
        if (this.processError) {
            try {
                const result = await this.actor.createMovieProject(to_candid_Project_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMovieProject(to_candid_Project_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPromptEntry(arg0: Prompt): Promise<Prompt> {
        if (this.processError) {
            try {
                const result = await this.actor.createPromptEntry(to_candid_Prompt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Prompt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPromptEntry(to_candid_Prompt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Prompt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMovieProject(arg0: ProjectId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMovieProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMovieProject(arg0);
            return result;
        }
    }
    async getAllUserProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProjects();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProjects();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMovieProject(arg0: ProjectId): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.getMovieProject(arg0);
                return from_candid_Project_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMovieProject(arg0);
            return from_candid_Project_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrompt(arg0: ProjectId): Promise<Prompt> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrompt(arg0);
                return from_candid_Prompt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrompt(arg0);
            return from_candid_Prompt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPromptEntries(): Promise<Array<Prompt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPromptEntries();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPromptEntries();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRolePromptEntries(): Promise<Array<Prompt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRolePromptEntries();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRolePromptEntries();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateMovieProject(arg0: ProjectId, arg1: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMovieProject(arg0, to_candid_Project_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMovieProject(arg0, to_candid_Project_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Metadata_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Metadata): Metadata {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_PromptType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PromptType): PromptType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Prompt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Prompt): Prompt {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Metadata]): Metadata | null {
    return value.length === 0 ? null : from_candid_Metadata_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        episodic: null;
    } | {
        nonLinear: null;
    } | {
        linear: null;
    }]): Variant_episodic_nonLinear_linear | null {
    return value.length === 0 ? null : from_candid_variant_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        large: null;
    } | {
        small: null;
    } | {
        medium: null;
    }]): Variant_large_small_medium | null {
    return value.length === 0 ? null : from_candid_variant_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        humorous: null;
    } | {
        dark: null;
    } | {
        serious: null;
    } | {
        lighthearted: null;
    }]): Variant_humorous_dark_serious_lighthearted | null {
    return value.length === 0 ? null : from_candid_variant_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        complex: null;
    } | {
        simple: null;
    } | {
        moderate: null;
    }]): Variant_complex_simple_moderate | null {
    return value.length === 0 ? null : from_candid_variant_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        animated: null;
    } | {
        standard: null;
    } | {
        musical: null;
    }]): Variant_animated_standard_musical | null {
    return value.length === 0 ? null : from_candid_variant_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        short: null;
    } | {
        featureLength: null;
    }]): Variant_short_featureLength | null {
    return value.length === 0 ? null : from_candid_variant_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    promptText: string;
    promptType: _PromptType;
    systemMessage: [] | [string];
    project: _ProjectId;
}): {
    title: string;
    promptText: string;
    promptType: PromptType;
    systemMessage?: string;
    project: ProjectId;
} {
    return {
        title: value.title,
        promptText: value.promptText,
        promptType: from_candid_PromptType_n20(_uploadFile, _downloadFile, value.promptType),
        systemMessage: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.systemMessage)),
        project: value.project
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    scenes: Array<_Scene>;
    metadata: [] | [_Metadata];
    user: Principal;
    logLine: string;
    synopsis: string;
    roles: Array<string>;
    prompts: Array<_Prompt>;
}): {
    title: string;
    scenes: Array<Scene>;
    metadata?: Metadata;
    user: Principal;
    logLine: string;
    synopsis: string;
    roles: Array<string>;
    prompts: Array<Prompt>;
} {
    return {
        title: value.title,
        scenes: value.scenes,
        metadata: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.metadata)),
        user: value.user,
        logLine: value.logLine,
        synopsis: value.synopsis,
        roles: value.roles,
        prompts: from_candid_vec_n41(_uploadFile, _downloadFile, value.prompts)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    narrativeStructure: [] | [{
            episodic: null;
        } | {
            nonLinear: null;
        } | {
            linear: null;
        }];
    originalLanguage: [] | [string];
    productionScope: [] | [{
            large: null;
        } | {
            small: null;
        } | {
            medium: null;
        }];
    visualStyle: [] | [string];
    tone: [] | [{
            humorous: null;
        } | {
            dark: null;
        } | {
            serious: null;
        } | {
            lighthearted: null;
        }];
    complexityLevel: [] | [{
            complex: null;
        } | {
            simple: null;
        } | {
            moderate: null;
        }];
    intendedAudience: [] | [string];
    genre: [] | [string];
    scriptFormat: [] | [{
            animated: null;
        } | {
            standard: null;
        } | {
            musical: null;
        }];
    runtime: [] | [{
            short: null;
        } | {
            featureLength: null;
        }];
}): {
    narrativeStructure?: Variant_episodic_nonLinear_linear;
    originalLanguage?: string;
    productionScope?: Variant_large_small_medium;
    visualStyle?: string;
    tone?: Variant_humorous_dark_serious_lighthearted;
    complexityLevel?: Variant_complex_simple_moderate;
    intendedAudience?: string;
    genre?: string;
    scriptFormat?: Variant_animated_standard_musical;
    runtime?: Variant_short_featureLength;
} {
    return {
        narrativeStructure: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.narrativeStructure)),
        originalLanguage: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.originalLanguage)),
        productionScope: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.productionScope)),
        visualStyle: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.visualStyle)),
        tone: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.tone)),
        complexityLevel: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.complexityLevel)),
        intendedAudience: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.intendedAudience)),
        genre: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.genre)),
        scriptFormat: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.scriptFormat)),
        runtime: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.runtime))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: null;
} | {
    scene: null;
} | {
    location: null;
}): PromptType {
    return "role" in value ? PromptType.role : "scene" in value ? PromptType.scene : "location" in value ? PromptType.location : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    episodic: null;
} | {
    nonLinear: null;
} | {
    linear: null;
}): Variant_episodic_nonLinear_linear {
    return "episodic" in value ? Variant_episodic_nonLinear_linear.episodic : "nonLinear" in value ? Variant_episodic_nonLinear_linear.nonLinear : "linear" in value ? Variant_episodic_nonLinear_linear.linear : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    large: null;
} | {
    small: null;
} | {
    medium: null;
}): Variant_large_small_medium {
    return "large" in value ? Variant_large_small_medium.large : "small" in value ? Variant_large_small_medium.small : "medium" in value ? Variant_large_small_medium.medium : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    humorous: null;
} | {
    dark: null;
} | {
    serious: null;
} | {
    lighthearted: null;
}): Variant_humorous_dark_serious_lighthearted {
    return "humorous" in value ? Variant_humorous_dark_serious_lighthearted.humorous : "dark" in value ? Variant_humorous_dark_serious_lighthearted.dark : "serious" in value ? Variant_humorous_dark_serious_lighthearted.serious : "lighthearted" in value ? Variant_humorous_dark_serious_lighthearted.lighthearted : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    complex: null;
} | {
    simple: null;
} | {
    moderate: null;
}): Variant_complex_simple_moderate {
    return "complex" in value ? Variant_complex_simple_moderate.complex : "simple" in value ? Variant_complex_simple_moderate.simple : "moderate" in value ? Variant_complex_simple_moderate.moderate : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    animated: null;
} | {
    standard: null;
} | {
    musical: null;
}): Variant_animated_standard_musical {
    return "animated" in value ? Variant_animated_standard_musical.animated : "standard" in value ? Variant_animated_standard_musical.standard : "musical" in value ? Variant_animated_standard_musical.musical : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    short: null;
} | {
    featureLength: null;
}): Variant_short_featureLength {
    return "short" in value ? Variant_short_featureLength.short : "featureLength" in value ? Variant_short_featureLength.featureLength : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Prompt>): Array<Prompt> {
    return value.map((x)=>from_candid_Prompt_n18(_uploadFile, _downloadFile, x));
}
function to_candid_Metadata_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Metadata): _Metadata {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Project_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): _Project {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_PromptType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PromptType): _PromptType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Prompt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Prompt): _Prompt {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    narrativeStructure?: Variant_episodic_nonLinear_linear;
    originalLanguage?: string;
    productionScope?: Variant_large_small_medium;
    visualStyle?: string;
    tone?: Variant_humorous_dark_serious_lighthearted;
    complexityLevel?: Variant_complex_simple_moderate;
    intendedAudience?: string;
    genre?: string;
    scriptFormat?: Variant_animated_standard_musical;
    runtime?: Variant_short_featureLength;
}): {
    narrativeStructure: [] | [{
            episodic: null;
        } | {
            nonLinear: null;
        } | {
            linear: null;
        }];
    originalLanguage: [] | [string];
    productionScope: [] | [{
            large: null;
        } | {
            small: null;
        } | {
            medium: null;
        }];
    visualStyle: [] | [string];
    tone: [] | [{
            humorous: null;
        } | {
            dark: null;
        } | {
            serious: null;
        } | {
            lighthearted: null;
        }];
    complexityLevel: [] | [{
            complex: null;
        } | {
            simple: null;
        } | {
            moderate: null;
        }];
    intendedAudience: [] | [string];
    genre: [] | [string];
    scriptFormat: [] | [{
            animated: null;
        } | {
            standard: null;
        } | {
            musical: null;
        }];
    runtime: [] | [{
            short: null;
        } | {
            featureLength: null;
        }];
} {
    return {
        narrativeStructure: value.narrativeStructure ? candid_some(to_candid_variant_n11(_uploadFile, _downloadFile, value.narrativeStructure)) : candid_none(),
        originalLanguage: value.originalLanguage ? candid_some(value.originalLanguage) : candid_none(),
        productionScope: value.productionScope ? candid_some(to_candid_variant_n12(_uploadFile, _downloadFile, value.productionScope)) : candid_none(),
        visualStyle: value.visualStyle ? candid_some(value.visualStyle) : candid_none(),
        tone: value.tone ? candid_some(to_candid_variant_n13(_uploadFile, _downloadFile, value.tone)) : candid_none(),
        complexityLevel: value.complexityLevel ? candid_some(to_candid_variant_n14(_uploadFile, _downloadFile, value.complexityLevel)) : candid_none(),
        intendedAudience: value.intendedAudience ? candid_some(value.intendedAudience) : candid_none(),
        genre: value.genre ? candid_some(value.genre) : candid_none(),
        scriptFormat: value.scriptFormat ? candid_some(to_candid_variant_n15(_uploadFile, _downloadFile, value.scriptFormat)) : candid_none(),
        runtime: value.runtime ? candid_some(to_candid_variant_n16(_uploadFile, _downloadFile, value.runtime)) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    promptText: string;
    promptType: PromptType;
    systemMessage?: string;
    project: ProjectId;
}): {
    title: string;
    promptText: string;
    promptType: _PromptType;
    systemMessage: [] | [string];
    project: _ProjectId;
} {
    return {
        title: value.title,
        promptText: value.promptText,
        promptType: to_candid_PromptType_n3(_uploadFile, _downloadFile, value.promptType),
        systemMessage: value.systemMessage ? candid_some(value.systemMessage) : candid_none(),
        project: value.project
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    scenes: Array<Scene>;
    metadata?: Metadata;
    user: Principal;
    logLine: string;
    synopsis: string;
    roles: Array<string>;
    prompts: Array<Prompt>;
}): {
    title: string;
    scenes: Array<_Scene>;
    metadata: [] | [_Metadata];
    user: Principal;
    logLine: string;
    synopsis: string;
    roles: Array<string>;
    prompts: Array<_Prompt>;
} {
    return {
        title: value.title,
        scenes: value.scenes,
        metadata: value.metadata ? candid_some(to_candid_Metadata_n9(_uploadFile, _downloadFile, value.metadata)) : candid_none(),
        user: value.user,
        logLine: value.logLine,
        synopsis: value.synopsis,
        roles: value.roles,
        prompts: to_candid_vec_n17(_uploadFile, _downloadFile, value.prompts)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_episodic_nonLinear_linear): {
    episodic: null;
} | {
    nonLinear: null;
} | {
    linear: null;
} {
    return value == Variant_episodic_nonLinear_linear.episodic ? {
        episodic: null
    } : value == Variant_episodic_nonLinear_linear.nonLinear ? {
        nonLinear: null
    } : value == Variant_episodic_nonLinear_linear.linear ? {
        linear: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_large_small_medium): {
    large: null;
} | {
    small: null;
} | {
    medium: null;
} {
    return value == Variant_large_small_medium.large ? {
        large: null
    } : value == Variant_large_small_medium.small ? {
        small: null
    } : value == Variant_large_small_medium.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_humorous_dark_serious_lighthearted): {
    humorous: null;
} | {
    dark: null;
} | {
    serious: null;
} | {
    lighthearted: null;
} {
    return value == Variant_humorous_dark_serious_lighthearted.humorous ? {
        humorous: null
    } : value == Variant_humorous_dark_serious_lighthearted.dark ? {
        dark: null
    } : value == Variant_humorous_dark_serious_lighthearted.serious ? {
        serious: null
    } : value == Variant_humorous_dark_serious_lighthearted.lighthearted ? {
        lighthearted: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_complex_simple_moderate): {
    complex: null;
} | {
    simple: null;
} | {
    moderate: null;
} {
    return value == Variant_complex_simple_moderate.complex ? {
        complex: null
    } : value == Variant_complex_simple_moderate.simple ? {
        simple: null
    } : value == Variant_complex_simple_moderate.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_animated_standard_musical): {
    animated: null;
} | {
    standard: null;
} | {
    musical: null;
} {
    return value == Variant_animated_standard_musical.animated ? {
        animated: null
    } : value == Variant_animated_standard_musical.standard ? {
        standard: null
    } : value == Variant_animated_standard_musical.musical ? {
        musical: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_short_featureLength): {
    short: null;
} | {
    featureLength: null;
} {
    return value == Variant_short_featureLength.short ? {
        short_: null
    } : value == Variant_short_featureLength.featureLength ? {
        featureLength: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PromptType): {
    role: null;
} | {
    scene: null;
} | {
    location: null;
} {
    return value == PromptType.role ? {
        role: null
    } : value == PromptType.scene ? {
        scene: null
    } : value == PromptType.location ? {
        location: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Prompt>): Array<_Prompt> {
    return value.map((x)=>to_candid_Prompt_n1(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
